#!/bin/bash

conf_id="$1"
export PGPASSWORD=bbb_core
val=$(psql -U bbb_core bbb_graphql -h 127.0.0.1 -w --csv -t -c "SELECT \"muteOnStart\" FROM meeting_voice  WHERE \"voiceConf\" = '${conf_id}'")
if [[ $val == "t" ]]; then
        echo "true";
else
        echo "false";
fi
