---

- name: mix cluster config into bbb_metor
  become: true
  ansible.builtin.set_fact:
     bbb_meteor: '{{ bbb_meteor | combine(bbb_meteor_cluster, recursive=True) }}'
  when: bbb_cluster_proxy_host | length > 0

- name: write custom meteor config
  become: true
  ansible.builtin.copy:
    content: '{{ bbb_meteor | to_nice_yaml }}'
    dest: /etc/bigbluebutton/bbb-html5.yml
    mode: 0644
    #  notify:
    #    - restart bbb-html5
