---

- name: create bbb-web service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/bbb-web.service.d/

- name: configure bbb-web application settings
  become: true
  template:
    src: application.conf
    dest: /usr/share/bbb-web/WEB-INF/classes/application.conf
  notify:
    - restart bbb-web

- name: configure bbb-web logging settings
  become: true
  template:
    src: logback.xml
    dest: /usr/share/bbb-web/WEB-INF/classes/logback.xml
  notify:
    - restart bbb-web

- name: deploy bbb-web service override configuration
  become: true
  template:
    src: bbb-web.override
    dest: /etc/systemd/system/bbb-web.service.d/override.conf
  notify:
    - reload systemd
    - restart bbb-web
