---

- name: override bbb-web service
  become: true
  template:
    src: bbb-web/bbb-web.service
    dest: /lib/systemd/system/bbb-web.service
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
    - restart bbb-web

- name: configure bbb-web application settings
  become: true
  template:
    src: bbb-web/logback.xml
    dest: /usr/share/bbb-web/WEB-INF/classes/logback.xml
    mode: 0644
  notify: restart bbb-web

- name: template bbb-web.properties
  become: true
  template:
    src: bbb-web/bbb-web.properties
    dest: /etc/bigbluebutton/bbb-web.properties
    owner: root
    group: root
    mode: 0600
  notify: restart bbb-web
