---

- name: create bbb-html5 service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/bbb-html5.service.d/
    mode: 0755

- name: deploy bbb-html5 service override configuration
  become: true
  template:
    src: bbb-html5.override
    dest: /etc/systemd/system/bbb-html5.service.d/override.conf
    mode: 0644
  notify:
    - reload systemd
    - restart bbb-html5

- name: deploy bbb-html5 mongoDB prepare script
  become: true
  copy:
    src: bbb-mongo-prepare.sh
    dest: /usr/bin/bbb-mongo-prepare.sh
    mode: 0755
  notify:
    - restart bbb-html5

- name: fix bbb-html5 service permissions
  become: true
  file:
    path: /lib/systemd/system/bbb-html5.service
    mode: 0644
    owner: root
    group: root
