---

- name: mix cluster config into bbb_metor
  become: true
  ansible.builtin.set_fact:
     bbb_meteor: '{{ bbb_meteor | combine(bbb_meteor_cluster, recursive=True) }}'
  when: bbb_cluster_proxy_host | length > 0

- name: write custom meteor config
  become: true
  ansible.builtin.copy:
    content: '{{ bbb_meteor | to_nice_yaml }}'
    dest: /etc/bigbluebutton/bbb-html5.yml
    mode: 0644
  notify:
    - restart bbb-html5

- name: increase max-old-space-size in frontends to 4096
  become: true
  ansible.builtin.replace:
    path: /usr/share/meteor/bundle/systemd_start_frontend.sh
    regexp: '(--max-old-space-size)=(\d*)'
    replace: '\1=4096'
  notify:
    - restart bbb-html5

- name: create bbb-html5 service override directories
  become: true
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/{{ item }}.d
    mode: 0755
  loop:
    - bbb-html5-frontend@.service
    - bbb-html5-backend@.service

- name: deploy bbb-html5-frontend@ service generic override configuration
  become: true
  ansible.builtin.template:
    src: bbb-html5-frontend@.override
    dest: /etc/systemd/system/bbb-html5-{{ item }}@.service.d/override.conf
    mode: 0644
  loop:
    - frontend
    - backend
  notify:
    - reload systemd
    - restart bbb-html5

- name: deploy bbb-html5-frontend@ and bbb-html5-backend@ service cluster override configuration
  become: true
  ansible.builtin.template:
    src: bbb-html5/cluster.conf
    dest: /etc/systemd/system/bbb-html5-{{ item }}@.service.d/cluster.conf
    mode: 0644
  when: bbb_cluster_proxy_host | length > 0
  loop:
    - frontend
    - backend
  notify:
    - reload systemd
    - restart bbb-html5

- name: set amount of html5 back- and frontends
  become: true
  ansible.builtin.template:
    src: bbb-html5/bbb-html5-with-roles.conf
    dest: /etc/bigbluebutton/bbb-html5-with-roles.conf
    mode: 0644
  notify:
    - restart bbb-html5
