---

- name: create bbb-web service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/bbb-web.service.d/
    mode: 0755

- name: remove bbb-web service override configuration
  become: true
  file:
    path: /etc/systemd/system/bbb-web.service.d/override.conf
    state: absent
  notify:
    - reload systemd
    - restart bbb-web

- name: configure bbb-web application settings
  become: true
  template:
    src: '{{ item }}'
    dest: '/usr/share/bbb-web/WEB-INF/classes/{{ item }}'
    mode: 0644
  loop:
    - logback.xml
  notify:
    - restart bbb-web

