---

- name: create bbb-web service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/bbb-web.service.d/
    mode: 0755

- name: deploy bbb-web service override configuration
  become: true
  template:
    src: bbb-web.override
    dest: /etc/systemd/system/bbb-web.service.d/override.conf
    mode: 0644
  notify:
    - reload systemd
    - restart bbb-web

- name: configure bbb-web application settings
  become: true
  template:
    src: '{{ item }}'
    dest: '/usr/share/bbb-web/WEB-INF/classes/{{ item }}'
    mode: 0644
  loop:
    - logback.xml
  notify:
    - restart bbb-web

- name: write custom meteor config
  become: true
  copy:
    content: '{{ bbb_meteor | to_nice_yaml }}'
    dest: /etc/bigbluebutton/bbb-html5.yml
  notify:
    - restart bbb-html5

- name: set amount of html5 back- and frontends
  become: true
  template:
    src: bbb-html5-with-roles.conf
    dest: /etc/bigbluebutton/bbb-html5-with-roles.conf
    mode: 0644
  notify:
    - restart bbb-web

- name: write localized guest wait page
  become: true
  copy:
    content: guest-wait.html
    dest: /usr/share/meteor/bundle/programs/server/assets/app/static/guest-wait/guest-wait.html

