---

- name: write custom meteor config
  become: true
  copy:
    content: '{{ bbb_meteor | to_nice_yaml }}'
    dest: /etc/bigbluebutton/bbb-html5.yml
    mode: 0644
  notify:
    - restart bbb-html5

- name: increase max-old-space-size in frontends to 4096
  become: true
  replace:
    path: /usr/share/meteor/bundle/systemd_start_frontend.sh
    regexp: '(--max-old-space-size)=(\d*)'
    replace: '\1=4096'
  notify:
    - restart bbb-html5

- name: create bbb-html5 service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/{{ item }}.d
    mode: 0755
  loop:
    - bbb-html5-frontend@.service
    - bbb-html5-backend@.service

- name: deploy bbb-html5-frontend@ service override configuration
  become: true
  template:
    src: bbb-html5-frontend@.override
    dest: /etc/systemd/system/bbb-html5-frontend@.service.d/override.conf
    mode: 0644
  notify:
    - reload systemd
    - restart bbb-html5

- name: deploy bbb-html5-backend@ service override configuration
  become: true
  template:
    src: bbb-html5-backend@.override
    dest: /etc/systemd/system/bbb-html5-frontend@.service.d/override.conf
    mode: 0644
  notify:
    - reload systemd
    - restart bbb-html5

- name: set amount of html5 back- and frontends
  become: true
  template:
    src: bbb-html5/bbb-html5-with-roles.conf
    dest: /etc/bigbluebutton/bbb-html5-with-roles.conf
    mode: 0644
  notify:
    - restart bbb-web

