---

- name: set correct owner for bbb-web files
  become: true
  file:
    dest: /usr/share/bbb-web/
    owner: root
    group: root
    recurse: true
    follow: false
  notify: restart bbb-web

- name: Create bbb-web service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/bbb-web.service.d/
    mode: "0755"

- name: Deploy bbb-web service override configuration
  become: true
  template:
    src: bbb-web/bbb-web.override
    dest: /etc/systemd/system/bbb-web.service.d/override.conf
    mode: "0644"
  notify:
    - reload systemd
    - restart bbb-web

- name: configure bbb-web application settings
  become: true
  template:
    src: bbb-web/logback.xml
    dest: /usr/share/bbb-web/WEB-INF/classes/logback.xml
    mode: 0644
  notify: restart bbb-web

- name: template bbb-web defaults
  become: true
  template:
    src: bbb-web/defaults
    dest: /etc/default/bbb-web
    mode: 0644
  notify: restart bbb-web

- name: template bbb-web.properties
  become: true
  template:
    src: bbb-web/bbb-web.properties
    dest: /etc/bigbluebutton/bbb-web.properties
    owner: bigbluebutton
    group: root
    mode: 0600
  notify: restart bbb-web
