---
- name: Update /etc/bigbluebutton akka configs
  become: true
  template:
    src: "{{ item }}"
    dest: "/etc/bigbluebutton/{{ item }}"
    owner: bigbluebutton
    group: root
    mode: '0600'
  loop:
    - bbb-apps-akka.conf
    - bbb-fsesl-akka.conf
  notify: restart bigbluebutton

- name: Update /etc/bigbluebutton/turn-stun-servers.xml
  become: true
  template:
    src: turn-stun-servers.xml
    dest: /etc/bigbluebutton/turn-stun-servers.xml
    owner: bigbluebutton
    group: root
    mode: '0600'
  notify: restart bigbluebutton

- name: serve recordings via https
  become: true
  lineinfile:
    path: /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
    regexp: "playback_protocol"
    line: "playback_protocol: https"
  notify: restart bigbluebutton

- name: set default presentation
  become: true
  copy:
    src: "{{ bbb_custom_presentation }}"
    dest: "/var/www/bigbluebutton-default/{{ bbb_custom_presentation_name | default(bbb_custom_presentation) }}"
    mode: 0644
  when: bbb_custom_presentation | length
