---
- name: Update /etc/bigbluebutton akka configs
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/bigbluebutton/{{ item }}"
    owner: bigbluebutton
    group: root
    mode: 0600
  loop:
    - bbb-apps-akka.conf
    - bbb-fsesl-akka.conf
  notify: restart bigbluebutton

- name: Update /etc/bigbluebutton/turn-stun-servers.xml
  become: true
  ansible.builtin.template:
    src: turn-stun-servers.xml
    dest: /etc/bigbluebutton/turn-stun-servers.xml
    owner: bigbluebutton
    group: root
    mode: 0600
  notify: restart bigbluebutton

- name: set default presentation
  become: true
  ansible.builtin.copy:
    src: "{{ bbb_custom_presentation }}"
    dest: "/var/www/bigbluebutton-default/{{ bbb_custom_presentation_name | default(bbb_custom_presentation) }}"
    mode: 0644
  when: bbb_custom_presentation | length
