---

- include: dialin_standalone.yml
  when: bbb_sipgw is not defined

- include: dialin_sipgw.yml
  when: bbb_sipgw is defined

- name: set bbb dialin number
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^defaultDialAccessNumber='
    line: 'defaultDialAccessNumber={{ bbb_sip_pretty_number }}'
  notify: reload bbb-web

- name: show dialin number in welcome message
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^defaultWelcomeMessageFooter='
    #line: 'defaultWelcomeMessageFooter=To join this meeting by phone, dial:<br>  %%DIALNUM%%<br>Then enter %%CONFNUM%% as the conference PIN number.'
    line: 'defaultWelcomeMessageFooter=Um dieser Konferenz per Telefon beizutreten, w&auml;hlen Sie <tt>%%DIALNUM%%</tt> und geben <tt>%%CONFNUM%%</tt> als Konferenz-PIN ein.<br><br><b>Hinweis:</b> Anrufer sind ggf. stummgeschaltet. Dr&uuml;cken Sie <tt>0</tt> um zu sprechen bzw. sich stummzuschalten.'
  notify: reload bbb-web
