---

- name: add config files for etherpad
  become: true
  ansible.builtin.template:
    src: "{{ item }}" 
    dest: "/etc/bigbluebutton/{{ item }}"
    mode: 0644
  loop:
     - etherpad.json
     - bbb-export-annotations.json
  notify:
    - restart etherpad
