---

- name: add bbb-export-annotations.json config file for etherpad
  become: true
  ansible.builtin.template:
    src: bbb-export-annotations.json
    dest: /etc/bigbluebutton/bbb-export-annotations.json
    mode: 0644
  notify:
    - restart etherpad
