---

# https://github.com/bigbluebutton/bigbluebutton/issues/11752
- name: fix service directory permissions
  become: true
  file:
    path: /usr/lib/systemd/system
    state: directory
    recurse: true
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX
