---

- name: delete freeswitch file logging config
  become: true
  file:
    state: absent
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/logfile.conf.xml
  notify: restart freeswitch

- name: create freeswitch service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/freeswitch.service.d/

- name: deploy freeswitch service override configuration
  become: true
  template:
    src: freeswitch.override 
    dest: /etc/systemd/system/freeswitch.service.d/override.conf
  notify:
    - reload systemd
    - restart freeswitch

- name: enable IPv6 in FreeSWITCH service 1/2
  become: true
  command:
    cmd: mv {{ item }}_ {{ item }}
    creates: "{{ item }}"
    removes: "{{ item }}_"
  with_items:
    - "/opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml"
    - "/opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml"
  when: bbb_freeswitch_ipv6
  notify:
  - restart freeswitch

- name: enable IPv6 in FreeSWITCH service 2/2
  become: true
  lineinfile:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
    regexp: '<param name="listen-ip" value="[a-fA-F0-9.:]+"/>'
    line: '<param name="listen-ip" value="::"/>'
  when: bbb_freeswitch_ipv6
  notify:
  - restart freeswitch

- name: disable IPv6 in FreeSWITCH service 1/2
  become: true
  command:
    cmd: mv {{ item }} {{ item }}_
    creates: "{{ item }}_"
    removes: "{{ item }}"
  with_items:
    - "/opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml"
    - "/opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml"
  when: not bbb_freeswitch_ipv6
  notify:
  - restart freeswitch

- name: disable IPv6 in FreeSWITCH service 2/2
  become: true
  lineinfile:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
    regexp: '<param name="listen-ip" value="[a-fA-F0-9.:]+"/>'
    line: '<param name="listen-ip" value="127.0.0.1"/>'
  when: not bbb_freeswitch_ipv6
  notify:
  - restart freeswitch

#- name: FreeSWITCH dialplan quality
#  become: true
#  replace:
#    backup: true
#    path: /opt/freeswitch/conf/dialplan/default/bbb_conference.xml
#    regexp: '<action application="conference" data="\$1@.*"\/>'
