---
- name: install haproxy
  become: true
  ansible.builtin.apt:
    pkg: haproxy

- name: template haproxy config
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    mode: 0644
  notify: reload haproxy
  loop:
    - haproxy/haproxy.cfg
    - haproxy/protocolmap

- name: template haproxy dehydrated hook
  become: true
  ansible.builtin.template:
    src: haproxy/deploy-cert
    dest: /etc/dehydrated/hooks.d/deploy-cert-haproxy
    group: root
    mode: 0750
  notify: 
    - run dehydrated deploy hook
    - reload haproxy

- name: ensure haproxy is enabled to start at boot
  become: true
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
  notify: restart haproxy

- name: check if bbb_ssl_cert exists
  become: true
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ bbb_hostname }}/fullchain.pem"
  register: bbbcert
