---

- name: install dependencies
  become: true
  ansible.builtin.apt:
    name: ["language-pack-en", "software-properties-common", "nodejs", "containerd", "openjdk-{{ bbb_java_version }}-jre-headless"]
    update_cache: true

- name: set version of java to use
  become: true
  ansible.builtin.file:
    src: "/usr/lib/jvm/java-{{ bbb_java_version }}-openjdk-amd64/bin/java"
    dest: /etc/alternatives/java
    state: link

- name: install bbb
  become: true
  ansible.builtin.apt:
    name: ["bigbluebutton", "bbb-playback-video"]

- name: install extra or updated packages
  become: true
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ bbb_additional_packages }}"
  when: bbb_additional_packages is defined
