---

- name: generate DTLS-SRTP certificate for kurento
  become: true
  shell:
    cmd: 'umask 137 && openssl req -x509 -new -nodes -newkey rsa:4096 -sha256 -days 3650 -subj "/C=BR/ST=Ottawa/O=BigBlueButton Inc./OU=Live/CN={{ inventory_hostname }}" -keyout /tmp/dtls-srtp-key.pem -out /tmp/dtls-srtp-cert.pem && cat /tmp/dtls-srtp-key.pem /tmp/dtls-srtp-cert.pem > /etc/kurento/dtls-srtp.pem && chgrp kurento /etc/kurento/dtls-srtp.pem && rm /tmp/dtls-srtp-key.pem /tmp/dtls-srtp-cert.pem'
    creates: /etc/kurento/dtls-srtp.pem
  notify: restart kurento

- name: use DTLS-SRTP for kurento
  become: true
  lineinfile:
    path: /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
    regexp: 'pemCertificateRSA='
    line: 'pemCertificateRSA=/etc/kurento/dtls-srtp.pem'
  notify: restart kurento

- name: create /opt/freeswitch/etc/freeswitch/tls/
  become: true
  file:
    name: /opt/freeswitch/etc/freeswitch/tls
    state: directory
    owner: freeswitch
    group: daemon
    mode: "0700"

- name: use DTLS-SRTP for freeswitch
  become: true
  copy:
    remote_src: True
    src: /etc/kurento/dtls-srtp.pem
    dest: /opt/freeswitch/etc/freeswitch/tls/dtls-srtp.pem
    group: daemon
    mode: 0640
  ignore_errors: "{{ ansible_check_mode }}"
  notify: restart freeswitch

- name: increase kernel max PID number
  become: true
  sysctl:
    name: kernel.pid_max
    value: "4194304"
    sysctl_file: /etc/sysctl.d/20-kurento.conf
  notify:
    - restart kurento
