- name: create kurento service overwrite directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/kurento-media-server.service.d/

- name: deploy kurento service overwrite configuration
  become: true
  template:
    src: kurento.overwrite 
    dest: /etc/systemd/system/kurento-media-server.service.d/override.conf
  notify:
    - reload systemd
    - restart kurento
