---

- name: add ansible specific repositorys
  ansible.builtin.import_tasks: repositories.yml

- name: installation of bbb and dependencies
  ansible.builtin.import_tasks: installation.yml

- name: configure nginx
  ansible.builtin.import_tasks: nginx.yml

- name: install and configure haproxy for turn / http traffic routing
  ansible.builtin.import_tasks: haproxy.yml
  when: bbb_unified_turn

- name: general bbb specific configurations
  ansible.builtin.import_tasks: config.yml

- name: fixup and configuration for bbb-web service
  ansible.builtin.import_tasks: bbb-web.yml

- name: fixup and configuration for bbb-html5 (cluster)service
  ansible.builtin.import_tasks: bbb-html5.yml

- name: configuration for bbb-graphql service
  ansible.builtin.import_tasks: bbb-graphql.yml

- name: configure etherpad export option
  ansible.builtin.import_tasks: etherpad.yml

- name: fixup, hardening and configuration of freeswitch service
  ansible.builtin.import_tasks: freeswitch.yml

- name: configure webrtc-sfu service
  ansible.builtin.import_tasks: webrtc-sfu.yml

- name: disable transparent huge pages
  ansible.builtin.import_tasks: thp.yml

- name: configuration of conference recording
  ansible.builtin.import_tasks: recording.yml

- name: configuration of SIP dialin
  ansible.builtin.import_tasks: dialin.yml
  when: bbb_sipgw is defined or bbb_sip_account is defined
