---
- import_tasks: repositories.yml

# Hotfix: This can be removed as soon as upstream fixes dependency issues
- import_tasks: libreoffice.yml

- import_tasks: installation.yml
- import_tasks: mongodb.yml
- import_tasks: nginx.yml
- import_tasks: config.yml
- import_tasks: kurento.yml
- import_tasks: bbb-web.yml
- import_tasks: bbb-html5.yml
- import_tasks: freeswitch.yml
- import_tasks: webrtc-sfu.yml
- import_tasks: stun-turn.yml
- import_tasks: thp.yml

- include: dialin_standalone.yml
  when: bbb_sipgw is not defined and bbb_sip_account is defined

- include: dialin_sipgw.yml
  when: bbb_sipgw is defined

- import_tasks: register_with_sipgw.yml
  when: bbb_sipgw is defined
