---
- import_tasks: repositories.yml
- import_tasks: installation.yml
- import_tasks: mongodb.yml


- name: Ensure nginx is started and enabled to start at boot.
  become: true
  systemd:
    name: nginx
    enabled: true
    state: started

- block:
  - name: create cert directory
    become: true
    file:
      path: "/etc/letsencrypt/live/{{ bbb_hostname }}"
      state: directory
      mode: 0755

  - name: deploy wildcard cert chain
    become: true
    copy:
      src: "{{ bbb_wildcard_cert }}/fullchain.pem"
      dest: "/etc/letsencrypt/live/{{ bbb_hostname }}/fullchain.pem"
      mode: 0644
    notify: reload nginx

  - name: deploy wildcard cert key
    become: true
    copy:
      src: "{{ bbb_wildcard_cert }}/privkey.pem"
      dest: "/etc/letsencrypt/live/{{ bbb_hostname }}/privkey.pem"
      mode: 0600
    notify: reload nginx
  when: bbb_wildcard_cert is defined

- name: Check if bbb_ssl_cert exists
  become: true
  stat:
    path: "/etc/letsencrypt/live/{{ bbb_hostname }}/fullchain.pem"
  register: bbbcert

- import_tasks: letsencrypt.yml
  when: not bbbcert.stat.exists

- import_tasks: config.yml
- import_tasks: nginx.yml
- import_tasks: kurento.yml
- import_tasks: bbb-web.yml
- import_tasks: bbb-html5.yml
- import_tasks: freeswitch.yml
- import_tasks: webrtc-sfu.yml
- import_tasks: stun-turn.yml
- import_tasks: thp.yml

- include: dialin_standalone.yml
  when: bbb_sipgw is not defined and bbb_sip_account is defined

- include: dialin_sipgw.yml
  when: bbb_sipgw is defined

- import_tasks: register_with_sipgw.yml
  when: bbb_sipgw is defined
