---
- name: Install required packages
  apt:
    name: ["language-pack-en", "software-properties-common", "openjdk-8-jdk"]
    update_cache: true
    state: present

- name: set version of java to use
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    dest: /etc/alternatives/java
    state: link
  notify: restart bigbluebutton

- import_tasks: locale.yml

- import_tasks: repositories.yml

- name: install bbb and dependencies
  apt:
    name: "{{ bbb_and_dependencies }}"

- name: install bbb-webhooks
  apt:
    name: "{{ bbb_webhooks }}"
  when: bbb_webhooks_enable
  notify: restart bigbluebutton

- import_tasks: mongodb.yml

- meta: flush_handlers

- name: Ensure mongod is started and enabled to start at boot.
  service:
    name: mongod
    enabled: true
    state: started

- name: Ensure nginx is started and enabled to start at boot.
  service:
    name: nginx
    enabled: true
    state: started

- name: Check if bbb_ssl_cert exists
  stat:
    path: "/etc/letsencrypt/live/{{ bbb_hostname }}/fullchain.pem"
  register: bbbcert

- import_tasks: letsencrypt.yml
  when: not bbbcert.stat.exists

- import_tasks: config.yml
- import_tasks: kurento.yml
- import_tasks: html5.yml
- import_tasks: freeswitch.yml
- import_tasks: webrtc-sfu.yml
