---
- name: Install required packages
  apt:
    name: ["language-pack-en", "software-properties-common", "openjdk-8-jdk"]
    update_cache: true

- name: set version of java to use
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    dest: /etc/alternatives/java
    state: link
  notify: restart bigbluebutton

- import_tasks: locale.yml

- import_tasks: repositories.yml

- name: install bbb and dependencies
  apt:
    name: ["mongodb-org", "bbb-html5", "bbb-check", "bigbluebutton"]

- import_tasks: mongodb.yml

- meta: flush_handlers

- name: Ensure mongod is started and enabled to start at boot.
  service:
    name: mongod
    enabled: true
    state: started

- name: Ensure nginx is started and enabled to start at boot.
  service:
    name: nginx
    enabled: true
    state: started

- block:
  - name: create cert directory
    become: true
    file:
      path: "/etc/letsencrypt/live/{{ bbb_hostname }}"
      state: directory
      mode: 0755

  - name: deploy wildcard cert chain
    become: true
    copy:
      src: "{{ bbb_wildcard_cert }}/fullchain.pem"
      dest: "/etc/letsencrypt/live/{{ bbb_hostname }}/fullchain.pem"
      mode: 0644
    notify: reload nginx

  - name: deploy wildcard cert key
    become: true
    copy:
      src: "{{ bbb_wildcard_cert }}/privkey.pem"
      dest: "/etc/letsencrypt/live/{{ bbb_hostname }}/privkey.pem"
      mode: 0600
    notify: reload nginx
  when: bbb_wildcard_cert is defined

- name: Check if bbb_ssl_cert exists
  stat:
    path: "/etc/letsencrypt/live/{{ bbb_hostname }}/fullchain.pem"
  register: bbbcert

- import_tasks: letsencrypt.yml
  when: not bbbcert.stat.exists

- import_tasks: config.yml
- import_tasks: nginx.yml
- import_tasks: kurento.yml
- import_tasks: bbb-html5.yml
- import_tasks: bbb-web.yml
- import_tasks: freeswitch.yml
- import_tasks: webrtc-sfu.yml
- import_tasks: thp.yml
- import_tasks: red5.yml

- import_tasks: dialin.yml
  when: bbb_sip_account.password | default(false) | bool
