---

- name: fix tmpfs size for mongodb
  become: true
  ansible.builtin.lineinfile:
    path: /usr/share/meteor/bundle/mongod_start_pre.sh
    regexp: "^  mount -t tmpfs"
    line: "  mount -t tmpfs -o size={{ bbb_mongodb_tempfssize }} tmpfs /mnt/mongo-ramdisk"
  notify:
    - stop mongo
    - restart mongo

- name: Ensure mongod is started and enabled to start at boot.
  become: true
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    state: started
