---

- name: Ensure mongodb4+ does not use nojournal - systemd
  become: true
  replace:
    dest: /etc/systemd/system/mongod.service
    regexp: ' --nojournal$'
    replace: ''
    backup: true
  when: bbb_mongodb_version|string == '4.2'
  notify:
    - reload systemd
    - restart mongo

- name: Ensure mongodb4+ does not use nojournal - config
  become: true
  template:
    src: mongo4-ramdisk.conf
    dest: /usr/share/meteor/bundle/mongo-ramdisk.conf
    mode: 0644
  when: bbb_mongodb_version|string == '4.2'
  notify:
    - restart mongo

- name: Ensure mongod is started and enabled to start at boot.
  become: true
  systemd:
    name: mongod
    enabled: true
    state: started
