---

- name: configure freeswitch to use SSL
  become: true
  lineinfile:
    path: /etc/bigbluebutton/nginx/sip.nginx
    regexp: "proxy_pass"
    line: "        proxy_pass https://{{ ansible_default_ipv4.address }}:7443;"
  notify: reload nginx

- name: create ssl folder for nginx
  become: true
  file:
    path: /etc/nginx/ssl
    mode: 0755
    state: directory

- name: Copy Predefined DH group ffdhe2048
  become: true
  copy:
    src: ffdhe4096.pem
    dest: /etc/nginx/ssl/ffdhe4096.pem
    mode: 0644
  notify: reload nginx

- name: copy bbb's nginx vhost
  become: true
  template:
    src: bigbluebutton
    dest: /etc/nginx/sites-available/bigbluebutton
    mode: 0644
  notify: reload nginx

