---
- name: template bbb nginx vhost
  become: true
  template:
    src: nginx/vhost.conf
    dest: /etc/nginx/vhosts.d/bigbluebutton.conf
    mode: 0644
  notify: reload nginx

- name: template bbb-html5 main config
  become: true
  template:
    src: nginx/bbb-html5.nginx
    dest: /usr/share/bigbluebutton/nginx/bbb-html5.nginx
    mode: 0644
  notify: reload nginx

- name: template bbb loadbalancer config
  become: true
  template:
    src: nginx/loadbalancer.nginx
    dest: /usr/share/bigbluebutton/nginx/loadbalancer.nginx
    mode: 0644
  notify: reload nginx

- name: template ip mapping for BBB
  become: true
  template:
    src: nginx/bigbluebutton_sip_addr_map.conf
    dest: /etc/nginx/conf.d/bigbluebutton_sip_addr_map.conf
    mode: 0644
  notify: reload nginx

- name: template bbb sip nginx config
  become: true
  template:
    src: nginx/sip.nginx
    dest: /usr/share/bigbluebutton/nginx/sip.nginx
    mode: 0644
  notify: reload nginx
