---
## FIXME: This needs to be overridden in /etc/bigbluebutton, depends
## on https://github.com/bigbluebutton/bigbluebutton/issues/14304
- name: write custom recording configuration
  become: true
  ansible.builtin.template:
    src: bbb-record/{{ item }}
    dest: /usr/local/bigbluebutton/core/scripts/{{ item }}
    mode: 0644
  loop:
    - bigbluebutton.yml
    - presentation.yml
  notify:
    - restart bbb-rap-caption-inbox
    - restart bbb-rap-resque-worker
