---

- name: register with sip gateway
  become: true
  delegate_to: "{{ bbb_sipgw }}"
  command:
    cmd: "fs_cli -x 'db insert/bbb_host_ip/{{ ansible_hostname }}/{{ ansible_default_ipv4.address }}'"
