---
- name: Download and install repository keys
  become: true
  ansible.builtin.get_url:
    url: "{{ item.key_url }}"
    dest: "{{ bbb_signed_by_dir }}/{{ item.key_file }}"
    mode: '0644'
  loop: "{{ bbb_repositories | selectattr('key_url', 'defined') }}"

- name: Add repositories with dedicated key files
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename | default(item.name) }}"
    validate_certs: false
    update_cache: true
  loop: "{{ bbb_repositories }}"
