---

- name: List old package sources
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: "*.list"
  register: _bbb_package_sources

- name: Clean up old package sources
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ _bbb_package_sources.files | map(attribute='path') }}"

- name: Add signed package repositories
  become: true
  ansible.builtin.deb822_repository:
    types: deb
    name: "{{ item.name }}"
    uris: "{{ item.uri }}"
    suites: "{{ item.suites | default(bbb_adr) }}"
    components: "{{ item.components | default('main') }}"
    signed_by: "{{ item.key_url }}"
  ignore_errors: "{{ ansible_check_mode }}"
  loop: "{{ bbb_repositories }}"
