---

- name: add repository keys
  become: true
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    id: "{{ item.id }}"
  loop:
    - url: "https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc"
      id: "770C4267C5E63474D171B60937B5DD5EFAB46452"
    - url: "https://pgp.mongodb.com/server-{{ bbb_mongodb_version }}.asc"
      id: "39BD841E4BE5FB195A65400E6A26B1AE64C3C388"
    - url: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"
      id: "9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280"

- ansible.builtin.set_fact:
    adr: "{{ ansible_distribution_release | lower }}"

- name: add repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://ubuntu.bigbluebutton.org/{{ adr }}-{{ bbb_repo_version }}/ bigbluebutton-{{ adr }} main"
    - "deb http://repo.mongodb.org/apt/ubuntu/ {{ adr }}/mongodb-org/{{ bbb_mongodb_version }} multiverse"
    - "deb https://deb.nodesource.com/node_{{ bbb_nodejs_version }}.x {{ adr }} main"
    - "ppa:bigbluebutton/support"
    - "ppa:rmescandon/yq"
