---

- name: add repository keys
  become: true
  apt_key:
    url: "{{ item.url }}"
    id: "{{ item.id }}"
  loop:
    - url: "https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc"
      id: "770C4267C5E63474D171B60937B5DD5EFAB46452"
    - url: "https://www.mongodb.org/static/pgp/server-{{ bbb_mongodb_version }}.asc"
      id: "E162F504A20CDF15827F718D4B7C549A058F8B6B"
    - url: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"
      id: "9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280"

- set_fact:
    adr: "{{ ansible_distribution_release | lower }}"

- name: remove legacy bbb repo names
  file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  with_items:
    - ubuntu_bigbluebutton_org_bionic_240.list
    - ubuntu_bigbluebutton_org_focal_250.list

- name: add dependency repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu {{ adr }} multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu {{ adr }} multiverse"
    - "deb http://archive.ubuntu.com/ubuntu {{ adr }}-updates multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu {{ adr }}-updates multiverse"
    - "deb http://repo.mongodb.org/apt/ubuntu/ {{ adr }}/mongodb-org/{{ bbb_mongodb_version }} multiverse"
    - "deb https://deb.nodesource.com/node_{{ bbb_nodejs_version }}.x {{ adr }} main"
    - "ppa:bigbluebutton/support"
    - "ppa:rmescandon/yq"
    - "ppa:certbot/certbot"

 # use uniform name to allow allow easy release pinning or upgrades to snapshots via bbb_repo_version
 # note: this will not allow downgrades!
- name: add bbb repository
  become: true
  apt_repository:
    repo: "deb https://ubuntu.bigbluebutton.org/{{ adr }}-{{ bbb_repo_version }}/ bigbluebutton-{{ adr }} main"
    mode: 0644
    filename: "ubuntu_bigbluebutton_org.list"

