---

- name: delete Transparent Huge Pages service file
  become: true
  file:
    path: /usr/lib/systemd/system/disable-transparent-huge-pages.service
    state: absent

- name: disable Transparent Huge Pages flag via grub
  lineinfile:
    path: /etc/default/grub
    regex: '^GRUB_CMDLINE_LINUX_DEFAULT="(((?!transparent_hugepage=never).)*)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 transparent_hugepage=never"'
    backrefs: yes
  notify: update grub
