---

- name: delete Transparent Huge Pages service file
  become: true
  file:
    path: /usr/lib/systemd/system/disable-transparent-huge-pages.service
    state: absent

- name: disable Transparent Huge Pages flag via grub
  copy:
    content: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT transparent_hugepage=never"'
    dest: /usr/default/grub.d/99-disable-tsh
    owner: root
    group: root
    mode: 0644
  notify: update grub
