---

- name: Create bigbluebutton group
  become: true
  ansible.builtin.group:
    name: bigbluebutton
    gid: "{{ bbb_gid }}"
    system: true

- name: Create bigbluebutton user if not existstant
  become: true
  ansible.builtin.user:
    name: bigbluebutton
    uid: "{{ bbb_uid }}"
    group: bigbluebutton
    shell: /bin/false
    home: /var/bigbluebutton
    createhome: yes
    system: true
