---
- name: create webrtc-sfu service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/bbb-webrtc-sfu.service.d/
    mode: 0755

- name: deploy webrtc-sfu service override configuration
  become: true
  template:
    src: bbb-webrtc-sfu.override
    dest: /etc/systemd/system/bbb-webrtc-sfu.service.d/override.conf
    mode: 0644
  notify:
    - reload systemd
    - restart bbb-webrtc-sfu

- name: create /etc/bigbluebutton/bbb-webrtc-sfu
  become: true
  file:
    state: directory
    path: /etc/bigbluebutton/bbb-webrtc-sfu
    mode: 0755

- name: write custom webrtc-sfu config
  become: true
  copy:
    content: '{{ bbb_webrtc_sfu_config | to_nice_yaml(indent=2, sort_keys=False) }}'
    dest: /etc/bigbluebutton/bbb-webrtc-sfu/production.yml
    mode: 0644
  notify:
    - restart bbb-webrtc-sfu

# https://github.com/bigbluebutton/bigbluebutton/issues/14066
# Remove me once BBB 2.4.1 is out
- name: apply BBB 2.4.0 workaround for firefox 96
  become: true
  patch:
    src: issue-14066-fix-firefox-96.patch
    basedir: /usr/local/bigbluebutton/bbb-webrtc-sfu
    strip: 1
  notify:
    - restart bbb-webrtc-sfu
