---
- name: create webrtc-sfu service override directory
  become: true
  file:
    state: directory
    path: /etc/systemd/system/bbb-webrtc-sfu.service.d/

- name: deploy webrtc-sfu service override configuration
  become: true
  template:
    src: bbb-webrtc-sfu.override
    dest: /etc/systemd/system/bbb-webrtc-sfu.service.d/override.conf
  notify:
    - reload systemd
    - restart bbb-webrtc-sfu

- name: create /etc/bigbluebutton/bbb-webrtc-sfu
  become: true
  file:
    state: directory
    path: /etc/bigbluebutton/bbb-webrtc-sfu

- name: write custom webrtc-sfu config
  copy:
    content: '{{ (bbb_webrtc_sfu_multikurento if bbb_multikurento else bbb_webrtc_sfu_singlekurento) | to_nice_yaml }}'
    dest: /etc/bigbluebutton/bbb-webrtc-sfu/production.yml
  notify:
    - restart bbb-webrtc-sfu
