---
- name: reload systemd
  become: true
  systemd:
    daemon_reload: true

- name: reload nginx
  become: true
  systemd:
    name: nginx
    state: reloaded

- name: restart nginx
  become: true
  systemd:
    name: nginx
    state: restarted

- name: restart bigbluebutton
  become: true
  command: bbb-conf --restart

- name: restart freeswitch
  become: true
  systemd:
    name: freeswitch
    state: restarted

- name: restart mongo
  become: true
  systemd:
    name: mongod
    state: restarted

- name: restart kurento
  become: true
  systemd:
    name: kurento-media-server
    state: restarted
